### ISSUE TITLE
where does the base64-encoded projectId come from?

### ISSUE THREAD

**Issue by iandouglas** [ookami-kb/gh-pr-project#2]
I'm interested to try this workflow, but you don't describe where to get the projectId value. It's not apparent to me where that comes from.

**Comment by ookami-kb** [comment]
Hi, `projectId` is ID of this project from GraphQL API. The simplest way to find it is using [GraphQL API Explorer](https://developer.github.com/v4/explorer/). E.g. you can get a list of the projects within some repository using the following query (just replace repository name and owner name with your values):

```graphql
query { 
  repository(name: "gh-pr-project", owner:"ookami-kb") {
    name
    projects(first: 100) {
      nodes {
        id
        name
      }
    }
  }
}
```

And you will get response that looks like this:

```json
{
  "data": {
    "repository": {
      "name": "gh-pr-project",
      "projects": {
        "nodes": [
          {
            "id": "MDc6UHJvamVjdDQ1NjA0NzI=",
            "name": "Test"
          },
          {
            "id": "MDc6UHJvamVjdDQ1NjA0NzM=",
            "name": "Test kanban"
          }
        ]
      }
    }
  }
}
```

**Comment by ookami-kb** [comment]
Added this info to readme.
